# in Nacos

#spring:
#  redis:
#    host: 192.168.205.128
#    port: 16379
#    timeout: 1000
#    jedis:
#      pool:
#        max-active: 8
#        max-wait: 1000
#        max-idle: 500
#        min-idle: 0
#baidu:
#  apikey: 3mWHEPREHzAxeCRq3z6xb8bR
#  secretkey: 33fUD7ztZm1v5uBIwiKZFICPIbcXhgju